
spring:
  application:
    name: TestAssignment
  profiles:
    active: default
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/usrdb
    hikari:
      connectionTimeout: 10000
      maximumPoolSize: 10
      minimumIdle: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true

server:
  port: 8090

user:
  age:
    min: 18
